include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/l10n/generated/**"
    - build/**
    - android/**
    - ios/**
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false      # zu streng fuer App-Code
    lines_longer_than_80_chars: false  # 100 ist unser Limit
    prefer_single_quotes: true
    always_use_package_imports: true
    avoid_print: true
